const types = {
    INIT_COUNTRIES: "INIT_COUNTRIES",
    GET_COUNTRIES: "GET_COUNTRIES",
    GET_COUNTRIES_FORCODE: "GET_COUNTRIES_FORCODE",
    GET_COUNTRY: "GET_COUNTRY",
    SET_COUNTRY: "SET_COUNTRY",
    SEARCH_COUNTRIES: "SEARCH_COUNTRIES",
    FILTER_COUNTRIES: "FILTER_COUNTRIES",
};

export default types;
